---
- name: Deploying html page on two ec2 machines
  hosts: remote
  become: yes
  # roles:
  #   - common
  tasks:
    - name: updating repositories in ec2 machines
      import_role: 
        name: common


    - name: delete a directory
      file:
        path: /var/www/html/pluto/
        state: absent

    - name: configuring webservers of ec2
      include_role:
        name: webserver



    - name: deleting default config of nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx service