    - name: updating packages repo in debian
      import_tasks: ubuntu.yaml
      when: ansible_facts['os_family']=='Debian'



    # - name: installing nginx in debian



    - name: updating package repo in redhat
      include_tasks: redhat.yaml
      when: ansible_facts['os_family']|lower=="redhat"