- name: copying nginx config to remotes ubuntu
  template: 
    src: /home/knoldus/Desktop/ansible-assignmentt/nginx-config.j2
    dest: /etc/nginx/conf.d/nginx.conf
    owner: root
    group: root
    mode: '0775'
  notify:
    - restart nginx service
  when: 'ansible_facts["os_family"]|lower=="{{ item.distro }}"'
  loop: "{{ configfiles }}"



# - name: copying the static html page to remotes ec2 machines
#   copy:
#     src: /home/knoldus/Downloads/marvel/html
#     dest: "{{ item.value }}"
#     owner: root
#     group: root
#     mode: '0664'
#   when: 'ansible_facts["os_family"]|lower=="{{ item.key }}"'
#   loop: "{{ htmlpaths|dict2items }}"


    #loops are pending
    # config files dono ki fix krni h
    # redhat nginx config change krna h playbook se